### ISSUE TITLE
Re-define "Auto-review" logic based on new use cases

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-curation-reporting#18]
During the 1/8/2024 cvc meeting a discussion on when 'auto-review' should be applied when moving curations for the `Curation QC` sheet to the `Review & Submit` sheet.

One note that was captured was "do not trigger auto-review if only the vcv ver is outdated (do not warn or color code)"

But a total review of how the auto-review should work is needed to assure all the use cases are covered.

**Comment by dazzariti** [comment]
Reviewed on Feb 9th call

"Auto Approve" - Flagging Candidate
"Auto Archive" - No Change

Need to further specify these rules with Pam and Julie

**Comment by dazzariti** [comment]
Review all together on April 12 call just to confirm this ticket is complete and everyone understands the changes to the sheet and how it works - incorporate any changes into the Review and Submission SOP

**Comment by dazzariti** [comment]
Discussed on April 12 CvC check in call - @jratliff1234 @ PamRobertson I will assign this ticket to you for now to add the specification for what rules Larry should follow to add Auto-Approve, Auto-Archive etc.

**Comment by dazzariti** [comment]
CvC team needs to review the Auto Review logic -  

Each annotation that has been selected and brought over from the Annotation tab to the Review tab in the Review & Submit v2 google sheet will go through the following process to help speed up the manual review process that takes place prior to submitting and processing the batch.
The automatic "auto" review process for annotations is based on the state of the SCV associated to the annotation at the point in time the annotation is pulled into or sent to the Review sheet.  The state of the data SHOULD be "refreshed" on the main Read.me tab so that it is as up-to-date as possible.
1. If the SCV has been deleted since the annotation was made then
	   Status = "Archive",  Note = "SCV has been deleted by submitter."
2. If the Annotation record is NOT the most recent for the given SCV then
	   Status = "", Note = "A newer annotation for this SCV takes precedence. Please verify that it is intentional."
3. If the submitter has updated the SCV and changed the classification then
	   Status = "", Note = "Re-curation needed. SCV classification has been updated by submitter."
4. If the Annotation is a "No Change" then
	   Status = "OK", Note = "Latest 'no change' actions auto reviewed for all curators, even if outdated as long as SCV has no classification change."
5. If the Annotation is a "Flagging Candidate" and the submitter has updated the SCV without changing the classification then
	   Status = "", Note = "Re-curation needed. SCV has been updated by submitter with no classification change."
6. If the Annotation is a "Flagging Candidate" and curator is on the "approved reviewers" list then
	   Status = "", Note = "Curator's annotation does not require manual review."
7. If the Annotation if a "Flagging Candidate" and the SCV is current and the curator is NOT on the "approved reviewers" list then
	   Status = "", Note = "Review needed. Curator's annotation requires manual review."
8. If the Annotation is neither "Flagging Candidate" nor "No Change" then
	   Status = "", Note = "Re-curation needed. Invalid or missing 'action' for this curation."

**Comment by dazzariti** [comment]
@jratliff1234 will add the Auto Logic rules to the CvC Project: How to Submit to ClinVar manual https://docs.google.com/document/d/1msp_vO0wp4yiIOJJGy27cY-A9Fp-yDss7ZKG2ICvfbw/edit?usp=sharing
