### ISSUE TITLE
CvC Annotation Log - update refresh capability

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#24]
Based on CvC meeting (03/25/24), the CvC annotation log takes ~2min to refresh as both the log and statistics tables are refreshed at the same time.
 
@larrybabb will separate the log and statistics tables so that they can refresh quicker.
This will be done by including a second refresh button for the statistics table. 

@RyanFWebb  @dazzariti

**Comment by larrybabb** [comment]
I added a 2nd "refresh" button at the top of the Statistics page. This refresh button should update all of the statitics tables on that page (as well as the annotation log). You should see the last refresh date on both the annotation log and statistics page update after it successfully completes.  

The original "Refresh" button on the Annotation Log page will ONLY update the annotation log. You should ONLY see the annotation log "last refresh date" update but NOT the "last refresh date" on the statistics page update.

The purpose of this is so that the performance of the annotation log refresh is faster so the curators that are checking their work do not have to wait for all the statistics tables to get refreshed when they are merely interested in seeing a new curation appear at the top of the log.

**Comment by dazzariti** [comment]
Reviewed with Julie, this looks good!
