### ISSUE TITLE
New value in the priority/QA sheet to identify VCV changes

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#5]
@dazzariti 
As per slack discussion 28th Sep.
Currently in the QA v3 sheet when Larry says a curated SCV has been updated, it **does not** consider within that VCV if other SCVs have been modified, added or removed. Larry plans to include an additional value in the priority/QA sheets to identify when there is a VCV version change due to any SCV update in that record.

**Comment by dazzariti** [comment]
@larrybabb This is related to this conversation regarding the first CvC ClinVar submission https://the-tgg.slack.com/archives/C01HY5FPJPJ/p1695763424868409

There may be a small bug in my clinvar submission report that is overlooking SCVs that get deleted. I will dig into this further, but it doesn't affect any of the actual data, just overstates the SCVs that need processing. I'll keep getting to the root discrepancy with the list of 30+ SCVs that Melissa identified to make sure we get this resolved.

But to be clear. The notion that I need to add an additional value to our priority/QA sheets so that we can determine when the VCV version changes for a previously curated SCV still needs to be done. This just came up at the last meeting. So right now, when I determine if something is "outdated" on the QA v3 sheet I'm really saying that the SCV version that was originally curated has been updated by the submitter. It does not yet take into consideration if any other SCV on the same VCV was modified, added or removed.

I also need to fix the bug in my "submissions checking" routine to assure I don't include "deleted" SCVs when sending the submissions to ClinVar. (another ticket to be created).

**Comment by larrybabb** [comment]
@PamRobertson or @dazzariti do you think I should add a separate flag to distinguish between when the precise SCV that was curated has been updated vs. when only the VCV version has changed?  I'm not sure if I should simply change the existing `outdated` flag on our scv curations to mean that either the scv was resubmitted by the submitter or any other scv on the vcv/variant was updated, added or deleted by the other submitters on this variant. I'm not sure if we want to keep the finer level of distinction or not. 

Please advise, either way is just as easy to implement, but it would mean that we would need to have two outdated flags vs one that could mean either situation.

**Comment by PamRobertson** [comment]
@larrybabb my vote would be the finer level of distinction. I think it's relevant to know when 
1) the SCV has been updated by the submitter
2) when another SCV in the variant record has been updated - potentially causing a new conflict, providing support for the SCV being annotated etc. Eitherway if it's not hard to implement I think it's worth distinguishing

**Comment by dazzariti** [comment]
Agree with @PamRobertson
