### ISSUE TITLE
Deleted SCVs sent to ClinVar

### ISSUE THREAD

**Issue by PamRobertson** [clingen-data-model/clinvar-curation-reporting#6]
@dazzariti 
As per slack discussion Sep 28th
Larry to fix the bug in his "submissions checking" routine to assure that "deleted" SCVs are not included when sending the submissions to ClinVar.

**Comment by dazzariti** [comment]
@larrybabb This is related to this conversation regarding the first CvC ClinVar submission https://the-tgg.slack.com/archives/C01HY5FPJPJ/p1695763424868409

There may be a small bug in my clinvar submission report that is overlooking SCVs that get deleted. I will dig into this further, but it doesn't affect any of the actual data, just overstates the SCVs that need processing.  I'll keep getting to the root discrepancy with the list of 30+ SCVs that Melissa identified to make sure we get this resolved.

But to be clear. The notion that I need to add an additional value to our priority/QA sheets so that we can determine when the VCV version changes for a previously curated SCV still needs to be done. This just came up at the last meeting. So right now, when I determine if something is "outdated" on the QA v3 sheet I'm really saying that the SCV version that was originally curated has been updated by the submitter. It does not yet take into consideration if any other SCV on the same VCV was modified, added or removed.

I also need to fix the bug in my "submissions checking" routine to assure I don't include "deleted" SCVs when sending the submissions to ClinVar. (another ticket to be created).

**Comment by larrybabb** [comment]
This issue was resolved. The root cause was an error in one of my procedures that returns a flag indicating whether the latest curation is deleted. It was not considering that the current version that was curated could be deleted. It errantly presumed that the version was incremented when the scv was deleted (which it isn't).
